### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by tmnyhbs** [seanboyce/ubiblio#2]
Not an issue per se, but curious if you’ve considered creating a docker image for this? 

This project looks like it would be a great fit for me and docker would really streamline the install process.

**Comment by seanboyce** [comment]
It's on the to-do list. A few people have requested this.

Someone helpfully contributed a Docker deployment -- you can use this now if that's helpful, although there's no image yet (check back soon).

**Comment by seanboyce** [comment]
Both Docker and a Docker Hub image are available now. Please enjoy!

**Comment by seanboyce** [comment]
Both Docker and a Docker Hub image are available now. Please enjoy!

**Comment by Nelluk** [comment]
I appreciate the work to get this docker-ized. My level of docker expertise is pretty limited, though. I am comfortable with projects that have a docker-compose file that just need a few lines edited. I am not really sure how to get started with just an image on docker hub. Perhaps @m0ngr31 could assist with either some setup steps or an example bare-bones docker compose file? Sorry for the annoying newbie request 😬

**Comment by m0ngr31** [comment]
@Nelluk 

A basic docker compose would end up looking like this:

```yml
services:
  ubiblio:
    container_name: ubiblio
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
    image: sean8196/ubiblio
    ports:
      - 8000:8000
    volumes:
      - /home/nelluk/dockers/ubiblio/app/config:/app/config
    restart: unless-stopped
```

Of course you'll want to add env vars for creating a user and stuff too.

**Comment by tmnyhbs** [comment]
Thank you @seanboyce for such quick work of this! 

Including my docker compose here as well with the environment variables added. Anything with { } needs to be changed out for your preferred info.

```
services:
ubiblio:
    container_name: ubiblio
    image: sean8196/ubiblio
    ports:
      - "8000:8000"
    volumes:
      - /home/{user}/.config/appdata/ubiblio:/app/config #
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={timezone}
      - CREATE_ADMIN_USER=true
      - ADMIN_USERNAME={ubiblio}
      - ADMIN_PASSWORD={ubibliopassword}
```
